#tomcat的相关配置
server: 
  port: 8800
  connection-timeout: 20000
  servlet:
    session:
      cookie:
        name: redpig-web
      timeout: 300
        
      
# 驱动配置信息
spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/yinger_mall?useUnicode=true&characterEncoding=utf-8
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 1 # 初始化大小，最小，最大
    min-idle: 3
    max-active: 20
    max-wait: 60000 # 配置获取连接等待超时的时间
    time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    min-evictable-idle-time-millis: 30000 # 配置一个连接在池中最小生存的时间，单位是毫秒
    validation-query: select 'x'
    test-while-idle: true
    test-on-borrow: true
    test-on-return: true
    pool-prepared-statements: true # 打开PSCache，并且指定每个连接上PSCache的大小
    max-pool-prepared-statement-per-connection-size: 20
#    filters: stat,wall # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    use-global-data-source-stat: true # 合并多个DruidDataSource的监控数据
  aop: 
    proxy-target-class: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# MyBatis 配置
mybatis:
  mapper-locations:
  - classpath:com/redpigmall/mapper/*.xml
  config-location: classpath:SqlMapConfig.xml

